BEGIN;
CREATE FUNCTION pg_temp.assert_ok(ok boolean, label text) RETURNS void LANGUAGE plpgsql AS $$ BEGIN IF ok IS DISTINCT FROM true THEN RAISE EXCEPTION 'FAILED: %',label; END IF; END $$;
CREATE FUNCTION pg_temp.expect_denied(q text) RETURNS void LANGUAGE plpgsql AS $$ BEGIN BEGIN EXECUTE q; EXCEPTION WHEN OTHERS THEN RETURN; END; RAISE EXCEPTION 'Unexpected success: %',q; END $$;
CREATE TEMP TABLE fixture(k text PRIMARY KEY,id uuid DEFAULT gen_random_uuid());
INSERT INTO fixture(k) VALUES('group'),('alice'),('bob'),('outsider'),('viewer'),('circle'),('othercircle'),('uid'),('bobuid'),('newuid'),('poll');
GRANT SELECT ON fixture TO authenticated,anon;
INSERT INTO groups(id,name,invite_code,owner_user_id) SELECT g.id,'Staging test',g.id::text,u.id FROM fixture g,fixture u WHERE g.k='group' and u.k='uid';
INSERT INTO members(id,group_id,name,role,schedule_visibility) SELECT f.id,g.id,f.k,case when f.k='viewer' then 'viewer' else 'member' end,'freebusy' FROM fixture f,fixture g WHERE f.k IN('alice','bob','outsider','viewer') AND g.k='group';
INSERT INTO member_devices(member_id,user_id) SELECT a.id,u.id FROM fixture a,fixture u WHERE (a.k='alice' AND u.k='uid') OR(a.k='bob' AND u.k='bobuid');
INSERT INTO shared_circles(id,group_id,name) SELECT f.id,g.id,f.k FROM fixture f,fixture g WHERE f.k IN('circle','othercircle') AND g.k='group';
INSERT INTO shared_circle_memberships(circle_id,member_id,role,member_type) SELECT c.id,m.id,case when m.k='alice' then 'admin' else 'member' end,case when m.k='viewer' then 'viewer' else 'working' end FROM fixture c,fixture m WHERE c.k='circle' AND m.k IN('alice','bob','viewer');
INSERT INTO shared_circle_memberships(circle_id,member_id,role) SELECT c.id,m.id,'admin' FROM fixture c,fixture m WHERE c.k='othercircle' AND m.k='outsider';
INSERT INTO days_off(group_id,member_id,day,entry_type,source,note) SELECT g.id,m.id,'2026-10-01','off','manual','secret' FROM fixture g,fixture m WHERE g.k='group' AND m.k IN('alice','bob','outsider','viewer');
INSERT INTO days_off(group_id,member_id,day,entry_type,source,shift_start_min,shift_end_min) SELECT g.id,m.id,'2026-09-30','shift','pdf',1200,480 FROM fixture g,fixture m WHERE g.k='group' AND m.k='bob';
INSERT INTO meal_availability_overrides(group_id,member_id,day,meal,status) SELECT g.id,m.id,'2026-10-01','lunch','unavailable' FROM fixture g,fixture m WHERE g.k='group' AND m.k='alice';
INSERT INTO group_polls(id,group_id,circle_id,title,created_by_member_id) SELECT p.id,g.id,c.id,'Private poll',m.id FROM fixture p,fixture g,fixture c,fixture m WHERE p.k='poll' AND g.k='group' AND c.k='othercircle' AND m.k='outsider';
INSERT INTO group_activity_feed(group_id,circle_id,actor_member_id,kind) SELECT g.id,c.id,m.id,'test' FROM fixture g,fixture c,fixture m WHERE g.k='group' AND c.k='othercircle' AND m.k='outsider';
SELECT set_config('request.jwt.claim.sub',(SELECT id::text FROM fixture WHERE k='uid'),true);
SET LOCAL ROLE authenticated;
SELECT pg_temp.assert_ok((SELECT count(*)=1 FROM days_off),'raw schedule is self-only');
SELECT pg_temp.assert_ok((SELECT count(*)=1 FROM meal_availability_overrides),'raw overrides self-only');
SELECT pg_temp.assert_ok((SELECT count(*)=0 FROM get_group_schedule_visible() WHERE member_id=(SELECT id FROM fixture WHERE k='bob') AND (note IS NOT NULL OR shift_start_min IS NOT NULL OR raw_value<>'PRIVATE')),'private peer projection');
SELECT pg_temp.assert_ok((SELECT count(*)=0 FROM get_group_polls()),'private poll hidden');
SELECT pg_temp.assert_ok((SELECT count(*)=0 FROM get_group_feed() WHERE kind='test'),'private feed hidden');
SELECT pg_temp.assert_ok((SELECT count(*)=2 FROM get_availability_v14('2026-10-01','2026-10-01')),'viewer and outsider excluded');
SELECT pg_temp.assert_ok((SELECT intervals='[{"start":0,"end":720,"status":"free"},{"start":720,"end":960,"status":"busy"},{"start":960,"end":1440,"status":"free"}]'::jsonb AND NOT full_day_off FROM get_availability_v14('2026-10-01','2026-10-01') WHERE member_id=(SELECT id FROM fixture WHERE k='alice')),'lunch override');
SELECT pg_temp.assert_ok((SELECT intervals='[{"start":0,"end":960,"status":"busy"},{"start":960,"end":1440,"status":"free"}]'::jsonb FROM get_availability_v14('2026-10-01','2026-10-01') WHERE member_id=(SELECT id FROM fixture WHERE k='bob')),'overnight recovery');
SELECT pg_temp.assert_ok((SELECT bool_and(NOT full_day_off) FROM get_availability_v14('2026-10-03','2026-10-03')),'unknown never free');
SELECT pg_temp.expect_denied('select * from member_availability_preferences');
SELECT pg_temp.expect_denied('select public.v13_2_log_app_activity(null,null,null,null,null)');
SELECT pg_temp.expect_denied(format('select remove_person_from_circle_v13(%L,%L)',(SELECT id FROM fixture WHERE k='circle'),(SELECT id FROM fixture WHERE k='alice')));
SELECT save_my_preferences_v14('{"commuteBefore":0,"commuteAfter":0,"postNightUntil":0,"minWindow":60,"preferredPeriod":"any"}');
SELECT pg_temp.assert_ok(get_my_preferences_v14()->>'postNightUntil'='0','preferences roundtrip');
SELECT set_recovery_key_v14(repeat('a',64));
SELECT pg_temp.assert_ok(preview_rota_import_v14(jsonb_build_array(jsonb_build_object('member_id',(SELECT id FROM fixture WHERE k='alice'),'day','2026-10-01')))->>'preserved'='1','manual preview');
SELECT pg_temp.assert_ok(apply_full_rota_import(jsonb_build_array(jsonb_build_object('member_id',(SELECT id FROM fixture WHERE k='alice'),'day','2026-10-01','entry_type','busy')),ARRAY[(SELECT id FROM fixture WHERE k='alice')],'2026-10-01','2026-10-01','test')=0,'manual import preserved');
SELECT save_circle_event_v14(null,(SELECT id FROM fixture WHERE k='circle'),'2026-10-01','Test plan',1200,null,null,'other',1500,'Europe/London');
SELECT pg_temp.expect_denied(format('select save_circle_event_v14(null,%L,current_date,%L,1200,null,null,%L,1199,%L)',(SELECT id FROM fixture WHERE k='circle'),'bad end','other','Europe/London'));
SELECT set_config('request.jwt.claim.sub',(SELECT id::text FROM fixture WHERE k='newuid'),true);
SELECT pg_temp.expect_denied(format('select remove_person_from_circle_v13(%L,%L)',(SELECT id FROM fixture WHERE k='circle'),(SELECT id FROM fixture WHERE k='bob')));
SELECT pg_temp.expect_denied(format('select delete_group_poll_v13_2(%L)',(SELECT id FROM fixture WHERE k='poll')));
SELECT pg_temp.expect_denied(format('select delete_group_poll_option_v13_2(%L,%L)',(SELECT id FROM fixture WHERE k='poll'),gen_random_uuid()));
SELECT pg_temp.assert_ok(recover_account_v14(repeat('a',64),'test device')=(SELECT id FROM fixture WHERE k='alice'),'recovery links identity');
SELECT set_config('request.jwt.claim.sub',gen_random_uuid()::text,true);
SELECT pg_temp.expect_denied(format('select recover_account_v14(%L)',repeat('a',64)));
RESET ROLE;
SET LOCAL ROLE anon;
SELECT pg_temp.expect_denied('select get_availability_v14(current_date,current_date)');
SELECT pg_temp.expect_denied('select set_recovery_key_v14(repeat(''b'',64))');
RESET ROLE;
SELECT 'PASS: staging SQL regression checks; fixtures rolled back' AS result;
ROLLBACK;

